version: 2
jobs:
  build:
    working_directory: ~/caseflow
    docker:
      # This is not quite the same as what we have locally, which is 2.2.4.
      - image: circleci/ruby:2.2.7-node-browsers
    steps:
      - checkout
      - run: gem install bundler
      - restore_cache: 
          key: bundler-{{ checksum 'Gemfile.lock' }}
          paths: vendor
      - run: bundle install --deployment --without development staging production
      - save_cache:
          key: bundler-{{ checksum 'Gemfile.lock' }}
          paths: vendor
