version: 2
jobs:
  build:
    working_directory: ~/caseflow
    docker:
      # This is not quite the same as what we have locally, which is 2.2.4.
      - image: circleci/ruby:2.2.7-node-browsers
    steps:
      - checkout
      - run: gem install bundler
      - run: npm -v
      - run: node -v
      - run: ruby -v
      - run: bundler -v
      - restore_cache: 
          key: bundler-{{ checksum "Gemfile.lock" }}
          paths: vendor
      - run: bundle install --deployment --without development staging production
      - save_cache:
          key: bundler-{{ checksum "Gemfile.lock" }}
          paths: vendor
      - restore_cache: 
          key: bundler-{{ checksum "client/npm-shrinkwrap.json" }}
          paths: client/node_modules
      - run: 
          command: npm install --no-optional
          working_directory: client
      - save_cache: 
          key: bundler-{{ checksum "client/npm-shrinkwrap.json" }}
          paths: client/node_modules
